name: google_sign_in_dartio
description: Flutter package for Google Sign-In built in dart and support both Mobile and Desktop environments.
version: 0.0.8
homepage: https://github.com/fluttercommunity/firebase_dart_sdk/tree/develop/google_sign_in_dart
commit: 89794a635a5efad6705e3d7ccc29e8139318d947

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.0
  google_sign_in_platform_interface: ^2.0.0
  shared_preferences: ^2.0.3
  url_launcher: ^6.0.2
  meta: ^1.3.0
  crypto: ^3.0.0
  http: ^0.13.0
  html_unescape: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter